/* Generated by Together */

package com.javera.ui.actions;

import java.awt.event.ActionEvent;
import java.util.EventObject;

/**
 * This interface should be implemented by components that wish to work
 * with Export actions.
 */
public interface Exportable {
    /**
     * Performs the Export action.
     */
    public void export( ActionEvent evt );

    /**
     * Implementing object should use this method to specify whether an Export
     * is currently performable.
     */
    public boolean isExportable( EventObject evt );
}
